name: Deploy CloudFormation Template

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload cloudformation.yaml to S3
      run: |
        aws s3 cp cloudformation.yaml s3://${{ secrets.S3_BUCKET_NAME }}/cloudformation.yaml

    - name: Update CloudFormation Stack
      run: |
        set -e
        OUTPUT=$(aws cloudformation update-stack \
          --stack-name ${{ secrets.CLOUDFORMATION_STACK_NAME }} \
          --template-url https://s3.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.S3_BUCKET_NAME }}/cloudformation.yaml \
          --capabilities CAPABILITY_IAM 2>&1) || true

        echo "$OUTPUT"

        if [[ "$OUTPUT" == *"No updates are to be performed"* ]]; then
          echo "✅ No changes to apply. Stack is already up to date."
          exit 0
        elif [[ "$OUTPUT" == *"ValidationError"* ]]; then
          echo "❌ Template validation failed. Aborting."
          exit 1
        fi

    - name: Wait for Stack Update to Complete
      run: |
        aws cloudformation wait stack-update-complete \
          --stack-name ${{ secrets.CLOUDFORMATION_STACK_NAME }}